package controller

import (
	"context"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/malico/docker-release/internal/config"
	"github.com/malico/docker-release/internal/provider"
	"github.com/malico/docker-release/internal/state"
	"github.com/malico/docker-release/internal/strategy"

	"github.com/docker/docker/api/types"
)

type configDir struct {
	dir string
	ext string
}

func (c *Controller) generateInitialConfigs(ctx context.Context, services map[serviceKey][]types.Container) {
	c.syncServicesConfigs(ctx, services, false, false)
}

// syncServicesConfigs parses labels, cleans stale config files, then generates
// and reloads provider config for each active service. checkHealth marks
// servers that fail their health check as down. skipDeploying skips services
// that already have a deployment in progress.
func (c *Controller) syncServicesConfigs(ctx context.Context, services map[serviceKey][]types.Container, checkHealth, skipDeploying bool) {
	activeConfigs := make(map[string]*config.ServiceConfig)

	for key, containers := range services {
		if len(containers) == 0 {
			continue
		}
		cfg, err := config.ParseLabels(containers[0].Labels)
		if err != nil {
			slog.Warn("skipping service config", "component", "controller", "service", key.deployKey(), "err", err)
			continue
		}
		c.resolveNginxProxyUpstream(ctx, cfg, containers)
		activeConfigs[key.deployKey()] = cfg
	}

	c.cleanStaleConfigs(activeConfigs)

	for key, containers := range services {
		cfg, ok := activeConfigs[key.deployKey()]
		if !ok {
			continue
		}
		if skipDeploying && c.shouldSkipRefresh(key) {
			continue
		}
		c.generateServiceConfig(ctx, key, cfg, containers, checkHealth)
	}
}

func (c *Controller) cleanStaleConfigs(activeConfigs map[string]*config.ServiceConfig) {
	active := make(map[configDir]map[string]bool)

	for name, cfg := range activeConfigs {
		ext, perService := provider.ConfigExt(cfg.Provider)
		if !perService {
			continue
		}
		if c.project == "" && !supportedInGlobalMode(cfg.Provider) {
			// Global mode does not manage per-service-file providers (see
			// generateServiceConfig), so never treat their files as stale.
			continue
		}
		dir := cfg.ConfigDir()
		if dir == "" {
			continue
		}
		markActiveConfig(active, configDir{dir: dir, ext: ext}, name)
		if cfg.Provider == config.ProviderNginx && cfg.NginxRouteDir != "" {
			cd := configDir{dir: cfg.NginxRouteDir, ext: ".location"}
			if active[cd] == nil {
				active[cd] = make(map[string]bool)
			}
			if cfg.NginxPath != "" {
				active[cd][name] = true
			}
		}
	}

	for cd, services := range active {
		entries, err := os.ReadDir(cd.dir)
		if err != nil {
			continue
		}

		for _, entry := range entries {
			if entry.IsDir() || !strings.HasSuffix(entry.Name(), cd.ext) {
				continue
			}

			service := strings.TrimSuffix(entry.Name(), cd.ext)
			if services[service] {
				continue
			}

			path := filepath.Join(cd.dir, entry.Name())

			content, err := os.ReadFile(path)
			if err != nil || !strings.HasPrefix(string(content), "# Generated by docker-release") {
				continue
			}

			if err := os.Remove(path); err != nil {
				slog.Error("error removing stale config", "component", "controller", "path", path, "err", err)
				continue
			}

			slog.Info("removed stale config", "component", "controller", "path", path)
		}
	}
}

func markActiveConfig(active map[configDir]map[string]bool, cd configDir, name string) {
	if active[cd] == nil {
		active[cd] = make(map[string]bool)
	}
	active[cd][name] = true
}

// supportedInGlobalMode reports whether a provider is safe to manage when one
// controller serves every Compose project. Per-service-file providers are not:
// each derives its config filename and upstream name from the bare service
// name, so two projects with the same service name would collide on disk and in
// the generated config. Only nginx-proxy (routes by VIRTUAL_HOST) and none
// (writes nothing) are project-safe.
func supportedInGlobalMode(p config.ProviderType) bool {
	_, perService := provider.ConfigExt(p)
	return !perService
}

func (c *Controller) generateServiceConfig(ctx context.Context, key serviceKey, cfg *config.ServiceConfig, containers []types.Container, checkHealth bool) {
	if c.project == "" && !supportedInGlobalMode(cfg.Provider) {
		slog.Error("provider not supported in global mode; skipping config (use nginx-proxy)",
			"component", "controller", "service", key.deployKey(), "provider", cfg.Provider)
		return
	}

	prov, err := c.factory.Provider(cfg)
	if err != nil {
		slog.Error("error building provider", "component", "controller", "service", key.deployKey(), "err", err)
		return
	}

	upstream, ok := c.deploymentStateUpstream(ctx, key, cfg, containers)
	if !ok {
		upstream = &provider.UpstreamState{
			Service:      key.service,
			UpstreamName: cfg.UpstreamName,
		}
	}

	if !ok {
		for _, ctr := range containers {
			addr, err := c.docker.ContainerAddr(ctx, ctr.ID)
			if err != nil {
				slog.Warn("resolving container address failed", "component", "controller", "container", ctr.ID[:12], "err", err)
				continue
			}

			down := false
			if checkHealth {
				healthy, err := c.docker.IsHealthy(ctx, ctr.ID)
				if err != nil {
					slog.Warn("checking container health failed", "component", "controller", "container", ctr.ID[:12], "err", err)
					continue
				}
				down = !healthy
			}

			upstream.Servers = append(upstream.Servers, provider.Server{
				Addr: addr,
				Down: down,
			})
		}
	}

	strategy.ApplyProviderSettings(cfg, upstream)

	// Bound provider I/O so a hung reload (e.g. stuck docker exec) can't wedge
	// the event-loop helpers that call this.
	opCtx, opCancel := context.WithTimeout(ctx, 60*time.Second)
	defer opCancel()

	if err := prov.GenerateConfig(opCtx, upstream); err != nil {
		slog.Error("error generating config", "component", "controller", "service", key.deployKey(), "err", err)
		return
	}

	if err := prov.Reload(opCtx); err != nil {
		slog.Error("error reloading provider", "component", "controller", "service", key.deployKey(), "err", err)
		c.refreshServiceConfigAfter(ctx, key, 5*time.Second)
		return
	}

	activeCount := 0
	for _, s := range upstream.Servers {
		if !s.Down {
			activeCount++
		}
	}

	slog.Info("generated config for service", "component", "controller", "service", key.deployKey(), "servers", len(upstream.Servers), "active", activeCount)
}

func (c *Controller) deploymentStateUpstream(ctx context.Context, key serviceKey, cfg *config.ServiceConfig, containers []types.Container) (*provider.UpstreamState, bool) {
	ds, err := c.managerFor(key.project).Load(key.service)
	if err != nil || ds.Status != state.StatusInProgress || len(ds.Containers.Stable) == 0 || len(ds.Containers.Canary) == 0 {
		return nil, false
	}

	weight := ds.CurrentWeight
	if weight <= 0 {
		switch ds.Strategy {
		case "canary":
			weight = cfg.Canary.StartPercentage
		case "blue-green":
			weight = cfg.BlueGreen.GreenWeight
		default:
			return nil, false
		}
	}

	if weight <= 0 || weight > 100 {
		return nil, false
	}

	containersByID := make(map[string]types.Container, len(containers))
	for _, ctr := range containers {
		containersByID[ctr.ID] = ctr
	}

	upstream := &provider.UpstreamState{
		Service:      key.service,
		UpstreamName: cfg.UpstreamName,
		Affinity:     cfg.Affinity,
	}

	stableWeight := 100 - weight
	c.addWeightedServers(ctx, upstream, containersByID, ds.Containers.Stable, stableWeight, "stable")
	c.addWeightedServers(ctx, upstream, containersByID, ds.Containers.Canary, weight, "canary")

	if len(upstream.Servers) == 0 {
		return nil, false
	}

	strategy.ApplyProviderSettings(cfg, upstream)
	return upstream, true
}

func (c *Controller) addWeightedServers(ctx context.Context, upstream *provider.UpstreamState, containersByID map[string]types.Container, ids []string, weight int, group string) {
	for _, id := range ids {
		ctr, ok := containersByID[id]
		if !ok {
			continue
		}

		addr, err := c.docker.ContainerAddr(ctx, ctr.ID)
		if err != nil {
			slog.Warn("resolving container address failed", "component", "controller", "container", ctr.ID[:12], "err", err)
			continue
		}

		upstream.Servers = append(upstream.Servers, provider.Server{
			Addr:   addr,
			Weight: weight,
			Group:  group,
		})
	}
}

func (c *Controller) refreshServiceConfig(ctx context.Context, key serviceKey) {
	containers, err := c.docker.ListManagedContainers(ctx, key.project)
	if err != nil {
		slog.Error("error listing containers", "component", "controller", "err", err)
		return
	}

	serviceContainers := filterServiceContainers(containers, key)

	if len(serviceContainers) == 0 {
		c.refreshAllConfigs(ctx)
		return
	}

	if c.shouldSkipRefresh(key) {
		return
	}

	cfg, err := config.ParseLabels(serviceContainers[0].Labels)
	if err != nil {
		slog.Error("error parsing labels", "component", "controller", "service", key.deployKey(), "err", err)
		return
	}

	c.resolveNginxProxyUpstream(ctx, cfg, serviceContainers)
	c.generateServiceConfig(ctx, key, cfg, serviceContainers, true)
}

func (c *Controller) refreshServiceConfigAfter(ctx context.Context, key serviceKey, delay time.Duration) {
	c.wg.Add(1)
	go func() {
		defer c.wg.Done()
		select {
		case <-time.After(delay):
		case <-ctx.Done():
			return
		}

		c.refreshServiceConfig(ctx, key)
	}()
}

func (c *Controller) refreshAllConfigs(ctx context.Context) {
	containers, err := c.docker.ListManagedContainers(ctx, c.project)
	if err != nil {
		slog.Error("error listing containers", "component", "controller", "err", err)
		return
	}
	c.syncServicesConfigs(ctx, groupContainersByService(containers), true, true)
}

func (c *Controller) shouldSkipRefresh(key serviceKey) bool {
	c.mu.Lock()
	_, deploying := c.deployments[key.deployKey()]
	c.mu.Unlock()

	if deploying {
		return true
	}

	ds, err := c.managerFor(key.project).Load(key.service)
	if err == nil && ds.Status == state.StatusInProgress && !ds.IsStale(state.DefaultStaleThreshold) {
		slog.Info("deployment in progress, skipping config refresh", "component", "controller", "service", key.deployKey())
		return true
	}

	return false
}
