package controller

import (
	"context"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/malico/docker-release/internal/config"
	"github.com/malico/docker-release/internal/provider"
	"github.com/malico/docker-release/internal/state"
	"github.com/malico/docker-release/internal/strategy"

	"github.com/docker/docker/api/types"
)

func (c *Controller) generateInitialConfigs(ctx context.Context, services map[string][]types.Container) {
	activeConfigs := make(map[string]*config.ServiceConfig)

	for name, containers := range services {
		if len(containers) == 0 {
			continue
		}

		cfg, err := config.ParseLabels(containers[0].Labels)
		if err != nil {
			slog.Warn("skipping initial config", "component", "controller", "service", name, "err", err)
			continue
		}

		c.resolveNginxProxyUpstream(ctx, cfg, containers)
		activeConfigs[name] = cfg
	}

	c.cleanStaleConfigs(activeConfigs)

	for name, cfg := range activeConfigs {
		c.generateServiceConfig(ctx, name, cfg, services[name], false)
	}
}

func (c *Controller) cleanStaleConfigs(activeConfigs map[string]*config.ServiceConfig) {
	type configDir struct {
		dir string
		ext string
	}

	active := make(map[configDir]map[string]bool)

	for name, cfg := range activeConfigs {
		var cd configDir

		switch cfg.Provider {
		case config.ProviderNginx:
			cd = configDir{dir: cfg.NginxConfigDir, ext: ".conf"}
		case config.ProviderAngie:
			cd = configDir{dir: cfg.AngieConfigDir, ext: ".conf"}
		case config.ProviderTraefik:
			cd = configDir{dir: cfg.TraefikConfigDir, ext: ".yml"}
		case config.ProviderCaddy:
			cd = configDir{dir: cfg.CaddyConfigDir, ext: ".caddy"}
		case config.ProviderHAProxy:
			cd = configDir{dir: cfg.HAProxyConfigDir, ext: ".cfg"}
		default:
			continue
		}

		if cd.dir == "" {
			continue
		}

		if active[cd] == nil {
			active[cd] = make(map[string]bool)
		}
		active[cd][name] = true
	}

	for cd, services := range active {
		entries, err := os.ReadDir(cd.dir)
		if err != nil {
			continue
		}

		for _, entry := range entries {
			if entry.IsDir() || !strings.HasSuffix(entry.Name(), cd.ext) {
				continue
			}

			service := strings.TrimSuffix(entry.Name(), cd.ext)
			if services[service] {
				continue
			}

			path := filepath.Join(cd.dir, entry.Name())

			content, err := os.ReadFile(path)
			if err != nil || !strings.HasPrefix(string(content), "# Generated by docker-release") {
				continue
			}

			if err := os.Remove(path); err != nil {
				slog.Error("error removing stale config", "component", "controller", "path", path, "err", err)
				continue
			}

			slog.Info("removed stale config", "component", "controller", "path", path)
		}
	}
}

func (c *Controller) generateServiceConfig(ctx context.Context, name string, cfg *config.ServiceConfig, containers []types.Container, checkHealth bool) {
	prov, err := c.factory.Provider(cfg)
	if err != nil {
		slog.Error("error building provider", "component", "controller", "service", name, "err", err)
		return
	}

	upstream, ok := c.deploymentStateUpstream(ctx, name, cfg, containers)
	if !ok {
		upstream = &provider.UpstreamState{
			Service:      name,
			UpstreamName: cfg.UpstreamName,
		}
	}

	if !ok {
		for _, ctr := range containers {
			addr, err := c.docker.ContainerAddr(ctx, ctr.ID)
			if err != nil {
				slog.Warn("resolving container address failed", "component", "controller", "container", ctr.ID[:12], "err", err)
				continue
			}

			down := false
			if checkHealth {
				healthy, err := c.docker.IsHealthy(ctx, ctr.ID)
				if err != nil {
					slog.Warn("checking container health failed", "component", "controller", "container", ctr.ID[:12], "err", err)
					continue
				}
				down = !healthy
			}

			upstream.Servers = append(upstream.Servers, provider.Server{
				Addr: addr,
				Down: down,
			})
		}
	}

	strategy.ApplyProviderSettings(cfg, upstream)

	// Bound provider I/O so a hung reload (e.g. stuck docker exec) can't wedge
	// the event-loop helpers that call this.
	opCtx, opCancel := context.WithTimeout(ctx, 60*time.Second)
	defer opCancel()

	if err := prov.GenerateConfig(opCtx, upstream); err != nil {
		slog.Error("error generating config", "component", "controller", "service", name, "err", err)
		return
	}

	if err := prov.Reload(opCtx); err != nil {
		slog.Error("error reloading provider", "component", "controller", "service", name, "err", err)
		c.refreshServiceConfigAfter(ctx, name, 5*time.Second)
		return
	}

	activeCount := 0
	for _, s := range upstream.Servers {
		if !s.Down {
			activeCount++
		}
	}

	slog.Info("generated config for service", "component", "controller", "service", name, "servers", len(upstream.Servers), "active", activeCount)
}

func (c *Controller) deploymentStateUpstream(ctx context.Context, name string, cfg *config.ServiceConfig, containers []types.Container) (*provider.UpstreamState, bool) {
	ds, err := c.stateManager.Load(name)
	if err != nil || ds.Status != state.StatusInProgress || len(ds.Containers.Stable) == 0 || len(ds.Containers.Canary) == 0 {
		return nil, false
	}

	weight := ds.CurrentWeight
	if weight <= 0 {
		switch ds.Strategy {
		case "canary":
			weight = cfg.Canary.StartPercentage
		case "blue-green":
			weight = cfg.BlueGreen.GreenWeight
		default:
			return nil, false
		}
	}

	if weight <= 0 || weight > 100 {
		return nil, false
	}

	containersByID := make(map[string]types.Container, len(containers))
	for _, ctr := range containers {
		containersByID[ctr.ID] = ctr
	}

	upstream := &provider.UpstreamState{
		Service:      name,
		UpstreamName: cfg.UpstreamName,
		Affinity:     cfg.Affinity,
	}

	stableWeight := 100 - weight
	c.addWeightedServers(ctx, upstream, containersByID, ds.Containers.Stable, stableWeight, "stable")
	c.addWeightedServers(ctx, upstream, containersByID, ds.Containers.Canary, weight, "canary")

	if len(upstream.Servers) == 0 {
		return nil, false
	}

	strategy.ApplyProviderSettings(cfg, upstream)
	return upstream, true
}

func (c *Controller) addWeightedServers(ctx context.Context, upstream *provider.UpstreamState, containersByID map[string]types.Container, ids []string, weight int, group string) {
	for _, id := range ids {
		ctr, ok := containersByID[id]
		if !ok {
			continue
		}

		addr, err := c.docker.ContainerAddr(ctx, ctr.ID)
		if err != nil {
			slog.Warn("resolving container address failed", "component", "controller", "container", ctr.ID[:12], "err", err)
			continue
		}

		upstream.Servers = append(upstream.Servers, provider.Server{
			Addr:   addr,
			Weight: weight,
			Group:  group,
		})
	}
}

func (c *Controller) refreshServiceConfig(ctx context.Context, serviceName string) {
	containers, err := c.docker.ListManagedContainers(ctx, c.project)
	if err != nil {
		slog.Error("error listing containers", "component", "controller", "err", err)
		return
	}

	serviceContainers := filterServiceContainers(containers, serviceName)

	if len(serviceContainers) == 0 {
		c.refreshAllConfigs(ctx)
		return
	}

	if c.shouldSkipRefresh(serviceName) {
		return
	}

	cfg, err := config.ParseLabels(serviceContainers[0].Labels)
	if err != nil {
		slog.Error("error parsing labels", "component", "controller", "service", serviceName, "err", err)
		return
	}

	c.resolveNginxProxyUpstream(ctx, cfg, serviceContainers)
	c.generateServiceConfig(ctx, serviceName, cfg, serviceContainers, true)
}

func (c *Controller) refreshServiceConfigAfter(ctx context.Context, serviceName string, delay time.Duration) {
	c.wg.Add(1)
	go func() {
		defer c.wg.Done()
		select {
		case <-time.After(delay):
		case <-ctx.Done():
			return
		}

		c.refreshServiceConfig(ctx, serviceName)
	}()
}

func (c *Controller) refreshAllConfigs(ctx context.Context) {
	containers, err := c.docker.ListManagedContainers(ctx, c.project)
	if err != nil {
		slog.Error("error listing containers", "component", "controller", "err", err)
		return
	}

	services := make(map[string][]types.Container)
	for _, ctr := range containers {
		name := ctr.Labels["com.docker.compose.service"]
		if name == "" {
			continue
		}
		services[name] = append(services[name], ctr)
	}

	activeConfigs := make(map[string]*config.ServiceConfig)
	for name, serviceContainers := range services {
		if len(serviceContainers) == 0 {
			continue
		}

		cfg, err := config.ParseLabels(serviceContainers[0].Labels)
		if err != nil {
			slog.Error("error parsing labels", "component", "controller", "service", name, "err", err)
			continue
		}

		activeConfigs[name] = cfg
	}

	c.cleanStaleConfigs(activeConfigs)

	for name, cfg := range activeConfigs {
		if c.shouldSkipRefresh(name) {
			continue
		}
		c.resolveNginxProxyUpstream(ctx, cfg, services[name])
		c.generateServiceConfig(ctx, name, cfg, services[name], true)
	}
}

func (c *Controller) shouldSkipRefresh(serviceName string) bool {
	c.mu.Lock()
	_, deploying := c.deployments[serviceName]
	c.mu.Unlock()

	if deploying {
		return true
	}

	ds, err := c.stateManager.Load(serviceName)
	if err == nil && ds.Status == state.StatusInProgress && !ds.IsStale(state.DefaultStaleThreshold) {
		slog.Info("deployment in progress, skipping config refresh", "component", "controller", "service", serviceName)
		return true
	}

	return false
}
