package provider

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/malico/docker-release/internal/docker"
	"github.com/malico/docker-release/internal/health"
)

type AngieProvider struct {
	configDir   string
	docker      *docker.Client
	serviceName string
	project     string
}

func NewAngie(configDir string, dockerClient *docker.Client, serviceName, project string) *AngieProvider {
	return &AngieProvider{
		configDir:   configDir,
		docker:      dockerClient,
		serviceName: serviceName,
		project:     project,
	}
}

// GenerateConfig creates an Angie upstream configuration file
func (p *AngieProvider) GenerateConfig(ctx context.Context, state *UpstreamState) error {
	if err := state.Validate(); err != nil {
		return err
	}

	conf := renderAngieUpstream(state)

	if err := os.MkdirAll(p.configDir, 0o755); err != nil {
		return fmt.Errorf("creating config dir: %w", err)
	}

	path := filepath.Join(p.configDir, state.Service+".conf")
	tmp := path + ".tmp"

	if err := os.WriteFile(tmp, []byte(conf), 0o644); err != nil {
		return fmt.Errorf("writing config: %w", err)
	}

	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("renaming config: %w", err)
	}

	health.RecordFile(path)
	return nil
}

func (p *AngieProvider) Reload(ctx context.Context) error {
	ctr, running, err := resolveProxyContainer(ctx, p.docker, p.project, p.serviceName, "angie")
	if err != nil {
		return fmt.Errorf("resolving angie container: %w", err)
	}

	if !matchesImage(ctr.Image, "angie", "nginx", "alpine") {
		return fmt.Errorf("container %q has unexpected image %q (want angie, nginx, or alpine-based)", ctr.ID[:12], ctr.Image)
	}

	if !running {
		return p.docker.Start(ctx, ctr.ID)
	}

	return p.docker.Exec(ctx, ctr.ID, []string{"angie", "-s", "reload"})
}

// renderAngieUpstream generates the upstream block for Angie
// Angie is a drop-in replacement for nginx, so the syntax is identical
func renderAngieUpstream(state *UpstreamState) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# Generated by docker-release for Angie\n")
	fmt.Fprintf(&b, "upstream %s_upstream {\n", state.ResolveUpstreamName())

	switch state.Affinity {
	case "cookie":
		if state.StickyLearnName != "" {
			zone := state.ResolveUpstreamName() + "_sessions"
			fmt.Fprintf(&b, "    sticky learn create=$upstream_cookie_%s lookup=$cookie_%s zone=%s:1m;\n",
				state.StickyLearnName, state.StickyLearnName, zone)
		} else {
			fmt.Fprintf(&b, "    sticky cookie %s path=/;\n", stickyCookieName(state))
		}
	case "ip":
		fmt.Fprintf(&b, "    ip_hash;\n")
	default:
		fmt.Fprintf(&b, "    least_conn;\n")
	}

	for _, s := range state.Servers {
		if s.Backup && !supportsAngieBackup(state.Affinity) {
			continue
		}

		fmt.Fprintf(&b, "    server %s", s.Addr)

		if s.Down {
			fmt.Fprintf(&b, " down")
		} else if s.Backup {
			fmt.Fprintf(&b, " backup")
		} else if s.Weight > 0 {
			fmt.Fprintf(&b, " weight=%d", s.Weight)
		}

		fmt.Fprintf(&b, ";\n")
	}

	if state.Keepalive > 0 {
		fmt.Fprintf(&b, "    keepalive %d;\n", state.Keepalive)
	}

	fmt.Fprintf(&b, "}\n")

	return b.String()
}
