package provider

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/malico/docker-release/internal/docker"
	"github.com/malico/docker-release/internal/health"
)

type CaddyProvider struct {
	configDir   string
	docker      *docker.Client
	serviceName string
	project     string
}

func NewCaddy(configDir string, dockerClient *docker.Client, serviceName, project string) *CaddyProvider {
	if configDir == "" {
		configDir = "/shared/caddy-config"
	}

	return &CaddyProvider{
		configDir:   configDir,
		docker:      dockerClient,
		serviceName: serviceName,
		project:     project,
	}
}

func (p *CaddyProvider) GenerateConfig(ctx context.Context, state *UpstreamState) error {
	if err := state.Validate(); err != nil {
		return err
	}

	conf := renderCaddyUpstream(state)

	if err := os.MkdirAll(p.configDir, 0o755); err != nil {
		return fmt.Errorf("creating config dir: %w", err)
	}

	path := filepath.Join(p.configDir, state.Service+".caddy")
	tmp := path + ".tmp"

	if err := os.WriteFile(tmp, []byte(conf), 0o644); err != nil {
		return fmt.Errorf("writing config: %w", err)
	}

	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("renaming config: %w", err)
	}

	health.RecordFile(path)
	return nil
}

func (p *CaddyProvider) Reload(ctx context.Context) error {
	ctr, running, err := resolveProxyContainer(ctx, p.docker, p.project, p.serviceName, "caddy")
	if err != nil {
		return fmt.Errorf("resolving caddy container: %w", err)
	}

	if !matchesImage(ctr.Image, "caddy", "alpine") {
		return fmt.Errorf("container %q has unexpected image %q (want caddy or alpine-based)", ctr.ID[:12], ctr.Image)
	}

	if !running {
		return p.docker.Start(ctx, ctr.ID)
	}

	return p.docker.Exec(ctx, ctr.ID, []string{"caddy", "reload", "--config", "/etc/caddy/Caddyfile"})
}

func renderCaddyUpstream(state *UpstreamState) string {
	var b strings.Builder

	name := state.ResolveUpstreamName()

	fmt.Fprintf(&b, "# Generated by docker-release for Caddy\n")
	fmt.Fprintf(&b, "(%s_upstream) {\n", name)

	fmt.Fprintf(&b, "    reverse_proxy")

	var active []Server
	for _, s := range state.Servers {
		if !s.Down && !s.Backup {
			active = append(active, s)
		}
	}

	for _, s := range active {
		fmt.Fprintf(&b, " %s", s.Addr)
	}
	fmt.Fprintf(&b, " {\n")

	hasWeights := false
	for _, s := range active {
		if s.Weight > 0 {
			hasWeights = true
			break
		}
	}

	switch state.Affinity {
	case "cookie":
		fmt.Fprintf(&b, "        lb_policy cookie %s\n", stickyCookieName(state))
	case "ip":
		fmt.Fprintf(&b, "        lb_policy ip_hash\n")
	default:
		if hasWeights {
			fmt.Fprintf(&b, "        lb_policy weighted_round_robin")
			for _, s := range active {
				w := s.Weight
				if w == 0 {
					w = 1
				}
				fmt.Fprintf(&b, " %d", w)
			}
			fmt.Fprintf(&b, "\n")
		} else {
			fmt.Fprintf(&b, "        lb_policy round_robin\n")
		}
	}

	if state.Keepalive > 0 {
		fmt.Fprintf(&b, "        transport http {\n")
		fmt.Fprintf(&b, "            keepalive_idle_conns_per_host %d\n", state.Keepalive)
		fmt.Fprintf(&b, "        }\n")
	}

	fmt.Fprintf(&b, "    }\n")

	fmt.Fprintf(&b, "}\n")

	return b.String()
}
