package provider

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/malico/docker-release/internal/docker"
	"github.com/malico/docker-release/internal/health"
)

type HAProxyProvider struct {
	configDir   string
	docker      *docker.Client
	serviceName string
	project     string
}

func NewHAProxy(configDir string, dockerClient *docker.Client, serviceName, project string) *HAProxyProvider {
	return &HAProxyProvider{
		configDir:   configDir,
		docker:      dockerClient,
		serviceName: serviceName,
		project:     project,
	}
}

func (p *HAProxyProvider) GenerateConfig(ctx context.Context, state *UpstreamState) error {
	if err := state.Validate(); err != nil {
		return err
	}

	conf := renderHAProxyBackend(state)

	if err := os.MkdirAll(p.configDir, 0o755); err != nil {
		return fmt.Errorf("creating config dir: %w", err)
	}

	path := filepath.Join(p.configDir, state.Service+".cfg")
	tmp := path + ".tmp"

	if err := os.WriteFile(tmp, []byte(conf), 0o644); err != nil {
		return fmt.Errorf("writing config: %w", err)
	}

	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("renaming config: %w", err)
	}

	health.RecordFile(path)
	return nil
}

func (p *HAProxyProvider) Reload(ctx context.Context) error {
	ctr, running, err := resolveProxyContainer(ctx, p.docker, p.project, p.serviceName, "haproxy")
	if err != nil {
		return fmt.Errorf("resolving haproxy container: %w", err)
	}

	if !matchesImage(ctr.Image, "haproxy", "alpine") {
		return fmt.Errorf("container %q has unexpected image %q (want haproxy or alpine-based)", ctr.ID[:12], ctr.Image)
	}

	if !running {
		return p.docker.Start(ctx, ctr.ID)
	}

	return p.docker.Exec(ctx, ctr.ID, []string{"sh", "-c", "kill -USR2 1"})
}

func renderHAProxyBackend(state *UpstreamState) string {
	var b strings.Builder

	name := state.ResolveUpstreamName()
	useCookie := state.Affinity == "cookie"

	fmt.Fprintf(&b, "# Generated by docker-release for HAProxy\n")
	fmt.Fprintf(&b, "backend %s_be\n", name)
	fmt.Fprintf(&b, "    mode http\n")
	fmt.Fprintf(&b, "    option http-keep-alive\n")
	fmt.Fprintf(&b, "    http-reuse safe\n")

	switch state.Affinity {
	case "cookie":
		fmt.Fprintf(&b, "    balance roundrobin\n")
		fmt.Fprintf(&b, "    cookie %s insert indirect nocache\n", stickyCookieName(state))
	case "ip":
		fmt.Fprintf(&b, "    balance source\n")
	default:
		fmt.Fprintf(&b, "    balance roundrobin\n")
	}

	for i, s := range state.Servers {
		fmt.Fprintf(&b, "    server s%d %s", i+1, s.Addr)

		if s.Weight > 0 {
			fmt.Fprintf(&b, " weight %d", s.Weight)
		}

		if s.Down {
			fmt.Fprintf(&b, " disabled")
		} else if s.Backup {
			fmt.Fprintf(&b, " backup")
		}

		if useCookie && !s.Backup {
			fmt.Fprintf(&b, " cookie s%d", i+1)
		}

		fmt.Fprintf(&b, "\n")
	}

	return b.String()
}
