package provider

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/malico/docker-release/internal/docker"
	"github.com/malico/docker-release/internal/health"
)

type NginxProvider struct {
	configDir   string
	routeDir    string
	routePath   string
	docker      *docker.Client
	serviceName string
	project     string
}

func NewNginx(configDir, routeDir, routePath string, dockerClient *docker.Client, serviceName, project string) *NginxProvider {
	return &NginxProvider{
		configDir:   configDir,
		routeDir:    routeDir,
		routePath:   routePath,
		docker:      dockerClient,
		serviceName: serviceName,
		project:     project,
	}
}

func (p *NginxProvider) GenerateConfig(ctx context.Context, state *UpstreamState) error {
	if err := state.Validate(); err != nil {
		return err
	}

	conf := renderUpstream(state)

	if err := os.MkdirAll(p.configDir, 0o755); err != nil {
		return fmt.Errorf("creating config dir: %w", err)
	}

	path := filepath.Join(p.configDir, state.Service+".conf")
	tmp := path + ".tmp"

	if err := os.WriteFile(tmp, []byte(conf), 0o644); err != nil {
		return fmt.Errorf("writing config: %w", err)
	}

	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("renaming config: %w", err)
	}

	health.RecordFile(path)

	if err := p.generateRoute(state); err != nil {
		return err
	}

	return nil
}

func (p *NginxProvider) generateRoute(state *UpstreamState) error {
	if p.routePath == "" {
		return nil
	}

	if err := os.MkdirAll(p.routeDir, 0o755); err != nil {
		return fmt.Errorf("creating route dir: %w", err)
	}

	path := filepath.Join(p.routeDir, state.Service+".location")
	tmp := path + ".tmp"

	if err := os.WriteFile(tmp, []byte(renderNginxRoute(state, p.routePath)), 0o644); err != nil {
		return fmt.Errorf("writing route config: %w", err)
	}

	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("renaming route config: %w", err)
	}

	health.RecordFile(path)
	return nil
}

func (p *NginxProvider) Reload(ctx context.Context) error {
	if os.Getenv("DR_BUNDLED_PROXY") == "nginx" {
		if _, err := os.Stat("/run/docker-release/nginx.started"); os.IsNotExist(err) {
			return nil
		}
	}

	ctr, running, err := resolveProxyContainer(ctx, p.docker, p.project, p.serviceName, "nginx")
	if err != nil {
		return fmt.Errorf("resolving nginx container: %w", err)
	}

	if ctr.Labels["com.malico.docker-release.bundled-proxy"] != "nginx" && !matchesImage(ctr.Image, "nginx", "alpine") {
		return fmt.Errorf("container %q has unexpected image %q (want nginx or alpine-based)", ctr.ID[:12], ctr.Image)
	}

	if !running {
		return p.docker.Start(ctx, ctr.ID)
	}

	return p.docker.Exec(ctx, ctr.ID, []string{"/usr/sbin/nginx", "-s", "reload"})
}

func renderUpstream(state *UpstreamState) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# Generated by docker-release\n")
	fmt.Fprintf(&b, "upstream %s_upstream {\n", state.ResolveUpstreamName())

	if state.Affinity == "ip" || state.Affinity == "cookie" {
		fmt.Fprintf(&b, "    ip_hash;\n")
	} else {
		fmt.Fprintf(&b, "    least_conn;\n")
	}

	for _, s := range state.Servers {
		if s.Backup && !supportsNginxBackup(state.Affinity) {
			continue
		}

		fmt.Fprintf(&b, "    server %s", s.Addr)

		if s.Down {
			fmt.Fprintf(&b, " down")
		} else if s.Backup {
			fmt.Fprintf(&b, " backup")
		} else if s.Weight > 0 {
			fmt.Fprintf(&b, " weight=%d", s.Weight)
		}

		fmt.Fprintf(&b, ";\n")
	}

	if state.Keepalive > 0 {
		fmt.Fprintf(&b, "    keepalive %d;\n", state.Keepalive)
	}

	fmt.Fprintf(&b, "}\n")

	return b.String()
}

func renderNginxRoute(state *UpstreamState, routePath string) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# Generated by docker-release\n")
	fmt.Fprintf(&b, "location %s {\n", routePath)
	fmt.Fprintf(&b, "    proxy_set_header Host $host;\n")
	fmt.Fprintf(&b, "    proxy_set_header X-Real-IP $remote_addr;\n")
	fmt.Fprintf(&b, "    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
	fmt.Fprintf(&b, "    proxy_set_header X-Forwarded-Proto $scheme;\n")
	fmt.Fprintf(&b, "    proxy_http_version 1.1;\n")
	fmt.Fprintf(&b, "    proxy_pass http://%s_upstream/;\n", state.ResolveUpstreamName())
	fmt.Fprintf(&b, "}\n")

	return b.String()
}
