package provider

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/malico/docker-release/internal/docker"
	"github.com/malico/docker-release/internal/health"
)

type NginxProvider struct {
	configDir string
	routeDir  string
	route     NginxRoute

	docker      *docker.Client
	serviceName string
	project     string
}

type NginxRoute struct {
	Host        string
	Path        string
	SSLCert     string
	SSLKey      string
	SSLRedirect bool
}

func NewNginx(configDir, routeDir string, route NginxRoute, dockerClient *docker.Client, serviceName, project string) *NginxProvider {
	return &NginxProvider{
		configDir:   configDir,
		routeDir:    routeDir,
		route:       route,
		docker:      dockerClient,
		serviceName: serviceName,
		project:     project,
	}
}

func (p *NginxProvider) GenerateConfig(ctx context.Context, state *UpstreamState) error {
	if err := state.Validate(); err != nil {
		return err
	}

	conf := renderUpstream(state)

	if err := os.MkdirAll(p.configDir, 0o755); err != nil {
		return fmt.Errorf("creating config dir: %w", err)
	}

	path := filepath.Join(p.configDir, state.Service+".conf")
	tmp := path + ".tmp"

	if err := os.WriteFile(tmp, []byte(conf), 0o644); err != nil {
		return fmt.Errorf("writing config: %w", err)
	}

	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("renaming config: %w", err)
	}

	health.RecordFile(path)

	if err := p.generateRoute(state); err != nil {
		return err
	}

	return nil
}

func (p *NginxProvider) generateRoute(state *UpstreamState) error {
	if p.routeDir == "" {
		return nil
	}

	if err := os.MkdirAll(p.routeDir, 0o755); err != nil {
		return fmt.Errorf("creating route dir: %w", err)
	}

	if p.route.Host == "" && p.route.Path == "" {
		return p.removeRouteFiles(state.Service)
	}

	if p.route.Host != "" {
		if err := p.writeRouteFile(state.Service, ".server", renderNginxServer(state, p.route)); err != nil {
			return err
		}
		return removeGeneratedFile(filepath.Join(p.routeDir, state.Service+".location"))
	}

	if err := p.writeRouteFile(state.Service, ".location", renderNginxLocation(state, p.route)); err != nil {
		return err
	}
	return removeGeneratedFile(filepath.Join(p.routeDir, state.Service+".server"))
}

func (p *NginxProvider) writeRouteFile(service, ext, content string) error {
	path := filepath.Join(p.routeDir, service+ext)
	tmp := path + ".tmp"

	if err := os.WriteFile(tmp, []byte(content), 0o644); err != nil {
		return fmt.Errorf("writing route config: %w", err)
	}

	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("renaming route config: %w", err)
	}

	health.RecordFile(path)
	return nil
}

func (p *NginxProvider) removeRouteFiles(service string) error {
	for _, ext := range []string{".location", ".server"} {
		if err := removeGeneratedFile(filepath.Join(p.routeDir, service+ext)); err != nil {
			return err
		}
	}
	return nil
}

func removeGeneratedFile(path string) error {
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	if !strings.HasPrefix(string(data), "# Generated by docker-release") {
		return nil
	}
	return os.Remove(path)
}

func (p *NginxProvider) Reload(ctx context.Context) error {
	if os.Getenv("DR_BUNDLED_PROXY") == "nginx" {
		if _, err := os.Stat("/run/docker-release/nginx.started"); os.IsNotExist(err) {
			return nil
		}
	}

	ctr, running, err := resolveProxyContainer(ctx, p.docker, p.project, p.serviceName, "nginx")
	if err != nil {
		return fmt.Errorf("resolving nginx container: %w", err)
	}

	if ctr.Labels["com.malico.docker-release.bundled-proxy"] != "nginx" && !matchesImage(ctr.Image, "nginx", "alpine") {
		return fmt.Errorf("container %q has unexpected image %q (want nginx or alpine-based)", ctr.ID[:12], ctr.Image)
	}

	if !running {
		return p.docker.Start(ctx, ctr.ID)
	}

	return p.docker.Exec(ctx, ctr.ID, []string{"/usr/sbin/nginx", "-s", "reload"})
}

func renderUpstream(state *UpstreamState) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# Generated by docker-release\n")
	fmt.Fprintf(&b, "upstream %s_upstream {\n", state.ResolveUpstreamName())

	if state.Affinity == "ip" || state.Affinity == "cookie" {
		fmt.Fprintf(&b, "    ip_hash;\n")
	} else {
		fmt.Fprintf(&b, "    least_conn;\n")
	}

	for _, s := range state.Servers {
		if s.Backup && !supportsNginxBackup(state.Affinity) {
			continue
		}

		fmt.Fprintf(&b, "    server %s", s.Addr)

		if s.Down {
			fmt.Fprintf(&b, " down")
		} else if s.Backup {
			fmt.Fprintf(&b, " backup")
		} else if s.Weight > 0 {
			fmt.Fprintf(&b, " weight=%d", s.Weight)
		}

		fmt.Fprintf(&b, ";\n")
	}

	if state.Keepalive > 0 {
		fmt.Fprintf(&b, "    keepalive %d;\n", state.Keepalive)
	}

	fmt.Fprintf(&b, "}\n")

	return b.String()
}

func renderNginxServer(state *UpstreamState, route NginxRoute) string {
	var b strings.Builder

	if route.SSLCert != "" {
		renderNginxServerBlock(&b, state, route, false, route.SSLRedirect)
		b.WriteString("\n")
		renderNginxServerBlock(&b, state, route, true, false)
		return b.String()
	}

	renderNginxServerBlock(&b, state, route, false, false)
	return b.String()
}

func renderNginxServerBlock(b *strings.Builder, state *UpstreamState, route NginxRoute, ssl, redirectOnly bool) {
	fmt.Fprintf(b, "# Generated by docker-release\n")
	fmt.Fprintf(b, "server {\n")
	if ssl {
		fmt.Fprintf(b, "    listen 443 ssl;\n")
	} else {
		fmt.Fprintf(b, "    listen 80;\n")
	}
	fmt.Fprintf(b, "    server_name %s;\n", normalizeNginxHost(route.Host))

	if ssl {
		fmt.Fprintf(b, "    ssl_certificate %s;\n", route.SSLCert)
		fmt.Fprintf(b, "    ssl_certificate_key %s;\n", route.SSLKey)
		fmt.Fprintf(b, "    include /etc/docker-release/nginx/ssl.d/*.conf;\n")
	}

	fmt.Fprintf(b, "\n")
	if redirectOnly {
		fmt.Fprintf(b, "    location / {\n")
		fmt.Fprintf(b, "        return 308 https://$host$request_uri;\n")
		fmt.Fprintf(b, "    }\n")
		fmt.Fprintf(b, "}\n")
		return
	}

	for _, line := range strings.Split(strings.TrimSuffix(renderNginxLocation(state, route), "\n"), "\n") {
		fmt.Fprintf(b, "    %s\n", line)
	}
	fmt.Fprintf(b, "    include /etc/docker-release/nginx/server.d/*.conf;\n")
	if ssl {
		fmt.Fprintf(b, "    include /etc/docker-release/nginx/https.d/*.conf;\n")
	}
	fmt.Fprintf(b, "}\n")
}

func renderNginxLocation(state *UpstreamState, route NginxRoute) string {
	var b strings.Builder
	path := route.Path
	if path == "" {
		path = "/"
	}

	fmt.Fprintf(&b, "# Generated by docker-release\n")
	fmt.Fprintf(&b, "location %s {\n", path)
	fmt.Fprintf(&b, "    proxy_set_header Host $host;\n")
	fmt.Fprintf(&b, "    proxy_set_header X-Real-IP $remote_addr;\n")
	fmt.Fprintf(&b, "    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
	fmt.Fprintf(&b, "    proxy_set_header X-Forwarded-Proto $scheme;\n")
	fmt.Fprintf(&b, "    proxy_http_version 1.1;\n")
	fmt.Fprintf(&b, "    proxy_pass http://%s_upstream/;\n", state.ResolveUpstreamName())
	fmt.Fprintf(&b, "}\n")

	return b.String()
}

func normalizeNginxHost(host string) string {
	return strings.Join(strings.FieldsFunc(host, func(r rune) bool { return r == ',' }), " ")
}
